package br.franke.lucas.type;

public enum RoadType {

    MIDDLE_ROAD,
    RIGHT_ROAD,
    LEFT_ROAD,
    TOP_ROAD,
    BOTTOM_ROAD,
    LEFT_TO_UP_CURVE_ROAD,
    RIGHT_TO_UP_CURVE_ROAD,
    LEFT_TO_DOWN_CURVE_ROAD,
    RIGHT_TO_DOWN_CURVE_ROAD,
    CORNER_TOP_LEFT_ROAD,
    CORNER_TOP_RIGHT_ROAD,
    CORNER_BOTTOM_LEFT_ROAD,
    CORNER_BOTTOM_RIGHT_ROAD,

}
